### ISSUE TITLE
xrootd: implement a FUSE backend for xrootd

### ISSUE THREAD

**Issue by sbinet** [go-hep/hep#174]

**Comment by EgorMatirov** [comment]
Regarding library choice... There is:
- https://github.com/bazil/fuse: 2 commits for the last 2 years, 61 open issues, 24 PRs. Supports Linux, OS X.
- https://github.com/hanwen/go-fuse: 15 commits since 2018, 18 open issues, 8 PRs. Has a list of known problems, but from first sight, there is nothing very scary. Supports Linux, OS X.
- https://github.com/jacobsa/fuse: not so much commits since 2018, 5 open issues, 3 PRs. Has some [application](https://github.com/gohxs/cloudmount) built on top of it (I am not saying that others don't have). Supports Linux, not sure about OS X.
- https://github.com/billziss-gh/cgofuse: a lot of commits since 2018, 4 open issues. Supports macOS,*BSD, Linux, Windows. Uses CGO.

`bazil/fuse` looks like a most popular choice, however, it bothers me that there is a number of open issues and not much development is happening.
`cgofuse` looks like a good promise, but I'm not sure that it's a good thing to use CGO. :)

So IMHO, priority is:
1) `cgofuse` if CGO is acceptable;
2) `go-fuse` since it has less open issues and more active development;
3) `bazil/fuse`.

What do you think?

**Comment by sbinet** [comment]
closed by #271 
(there are missing syscalls such as `hardlink` and `symlink` but these aren't available from the `xrootd` protocol.)
