### ISSUE TITLE
groot/rtree: considering adding TTreeFriend

### ISSUE THREAD

**Issue by rmadar** [go-hep/hep#723]
It would be nice to have the possibility to "pair" several trees together - as discussed in https://github.com/rmadar/tree-gonalyzer/issues/15. This would correspons to a "join" of databases or to a `numpy.hstack()` in python. ROOT offers the `TTreeFriend` interface to do this. From the user side, this would look like:
```go
// Get two trees 
tree1 := file1.Get("t1")(.rtree.Tree)
tree2 := file2.Get("t2")(.rtree.Tree)

// Numpy-like syntax
tree := rtree.Hstack(tree1, tree2)

// Database-like syntax
tree := rtree.Join(tree1, tree2)

// ROOT-like syntax
tree1.AddFriend(tree2)

// Assuming "one" would be stored in tree1 and "two" in tree2,
// one could access both info in the same way:
r := rtree.NewReader(tree, []rtree.ReadVar{
        {Name: "one", Value: &v1},
        {Name: "two", Value: &v2},
    } 
```
Ideally, this would have to be compatible with `rtree.FormulaFunc` in order to keep the same workflow.

**Comment by sbinet** [comment]
instead of tacking this on the `rtree.Tree` interface, I think I would go with actually adding a new (private to `rtree`) type, that would implement `rtree.Tree`.
doing the same trick than for `TChain` and the `rtree.Chain{,Of}` function, basically.

_i.e.:_
```go
// Join returns a new Tree that represents the logical join of the input trees.
// The returned tree will contain all the columns of all the input trees.
// Join errors out if the input trees do not have the same amount of entries.
// Join errors out if the input slice of trees is empty.
// Join errors out if two trees have each a column with the same name.
func Join(trees ...Tree) (Tree, error) { ... }
```

the last limitation could be lifted.
I suspect the most common use case for having 2 trees with branches/columns with the same name is a bkg/sig comparison. (so I guess it's fairly common).

in your original issue, you hinted at namespacing the `rvar` names with the tree name. (well, that's what ROOT does, so it makes sense)
but IIRC, you namespaced only the `rvar`s from the friend trees.
I'd err on requiring namespacing all of them (to handle the `Join` use case) or none (the normal use case.)

another possibility, would be to `Join` a slice of `rtree.Reader`s instead of `rtree.Tree`s.
not sure what's best.

WDYT?

**Comment by sbinet** [comment]
another open issue:
- what should we do, how should we handle a "joined" tree that is being copied to a new output tree (via `rtree.Copy(dst Writer, src Tree) (int64, error)`) ?

**Comment by rmadar** [comment]
This approach would perfect! Here are some comments:

> I suspect the most common use case for having 2 trees with branches/columns with the same name is a bkg/sig comparison. (so I guess it's fairly common).

Actually, I have never used/heard about this use case of TTreeFriend (one would just use two trees). I would tend to agree to keep the last limitation as an error, as least in a first step - as you proposed.

> I'd err on requiring namespacing all of them (to handle the Join use case) or none (the normal use case.)

Given the comment above, I'd say we could even leave the namespacing out of the game (*i.e* assuming that all columns must have different names across all trees). This could be a starting point at least?

> another possibility, would be to Join a slice of rtree.Readers instead of rtree.Trees.

If I understand correctly, this would implies to keep track of which original tree has the variable - which is a bit less straightforward from the user side. But maybe I missed a point.

**Comment by sbinet** [comment]
ok. if we don't allow branch collisions, then everything is easier.

**Comment by sbinet** [comment]
@rmadar please have a look at #726.
it should do what you want :)

**Comment by rmadar** [comment]
I'll try this, great!! Thanks
