### ISSUE TITLE
groot/rtree: same baskets loaded multiple times when loading entry by first seeking to it

### ISSUE THREAD

**Issue by datoux** [go-hep/hep#772]
In file branch.go  and function  **func (b \*tbranch) loadBasket(entry int64)**  the same baskets are loaded multiple times when not scanning the file from the beginning, but first seeking to an entry and reading following entries. 

The problem is with adding loaded  baskets in the branch.baskets array. If scanning from the beginning the baskets index corresponds to the index returned by **ib := b.findBasketIndex(entry)**. If first seeking to some entry, there is indexes mismatch. Probably it would be better to use map instead of array with basket ids, or look for the correct baskets in baskets array e.g. by offset in the file

**Comment by sbinet** [comment]
yes, you're right (and that's why groot has been -for the longest time- 2x slower than ROOT to read data).

but now, I *believe* that with the code in `rbranch.go`, `rbasket.go` and `bkreader.go`, this isn't the case anymore.
(actually, with that code, exercized by the "new" [rtree.NewReader](https://godoc.org/go-hep.org/x/hep/groot/rtree#NewReader), groot is 2x _faster_ than ROOT to read data.)

do you confirm my assessment above?

(I need to remove the old code, but figured I should first make sure all the 't's were crossed and all the 'i's were dotted. that's slightly related to https://github.com/go-hep/hep/issues/641)

**Comment by sbinet** [comment]
I've created https://github.com/go-hep/hep/issues/773 for the `groot/rtree` old-reading-code cleaning part.

**Comment by datoux** [comment]
I see, I didn't notice the new implementations. I will try it out.

**Comment by datoux** [comment]
For scannig sequential data the new reader works fine. Is the Scanner going to be deprecated ? In my case, I have to sometimes search for the entry in a root file by my binary search - I need to do a lot of seeks and reading just one entry. In the case of the new Reader interface, I would have to create a rtree.NewReader object each time. Can there be a Seek function or range parameter to Read function ?

**Comment by sbinet** [comment]
Scanner will indeed be deprecated when I am sure everything can be done w/ the new Reader.
(a first step will be to implement Scanner in terms of Reader)

yes, one can read over a range of entries:
https://godoc.org/go-hep.org/x/hep/groot/rtree#example-Reader--WithRange

one could imagine (instead of re-creating a `Reader` anew) introducing a new method:
```go
func (r *Reader) Reset(opts ...ReadOption) error { ... }
```

which could be used like so:
```go
r, err := rtree.NewReader(t, rvars)
// ...
err = r.Reset(rtree.WithRange(42, 43))
// ...
err = r.Reset(rtree.WithRange(0, -1))
```

WDYT?

**Comment by datoux** [comment]
Yes, I think that would work.

**Comment by sbinet** [comment]
great.

I'd be interested in knowing what kind of read pattern you are doing? what's the use case?
this could perhaps hint at a possible better API...

**Comment by datoux** [comment]
We have data from radiation detectors (pixel detectors Timepix https://advacam.com/1720.html) saved in root files. The root files contain the raw data (pixel matrixes - frame) and analyzed data found particle tracks (clusters) and their parameters (dose rate, energy, morphologic parameters, etc.) Each frame/cluster has timestamp. We have a big "database" of these data in many root files. I am writing a visualization and processing application that can find a certain frame/cluster and get its data and parameters. Therefore I need sometimes to search root file quickly (binary search) to find the right data and then scan multiple entries to get all the data corresponding to a single frame/cluster.  Sometimes I just need to scan many items from certain index to calculate some statistics.

**Comment by sbinet** [comment]
nice.

(if possible, I'd love to put you/your-team on the [go-hep.org/users](https://go-hep.org/users) list)

**Comment by datoux** [comment]
Sure, no problem. I don't have any publications yet with the go implementation - it is still in development. There is this presentation: https://indico.cern.ch/event/694586/contributions/2928565/attachments/1615854/2568015/TiS_NASA_Operations.pdf
